config/routes.rb
BroadcastWeb::Application.routes.draw do

  root to: 'pages#home'

  get 'transcoder_console', controller: :TranscoderConsole, action: :index
  post 'transcoder_console/perform'

  get 'transcoder_test', controller: :TranscoderTest, action: :index
  post 'transcoder_test/perform'
  get 'transcoder_test/status'
  get 'transcoder_test/host',controller: :TranscoderTest, action: :change_transcoder

  get 'advanced', controller: :Pages, action: :advanced
  get 'monitoring', controller: :Pages, action: :monitoring

  get '/admin/', controller: :Pages, action: :admin

  namespace :admin do
    resources :captures
    resources :sources
    resources :presets
    resources :schemes

    resources :transcoders do
      member do
        get :action
        get :create_slot
        get :start_slot
        get :stop_slot
        get :slots_status
        get :get_slots
        delete :delete_slot
      end
    end

    resources :events do
      member do
        get :action
        get :add_slot
        get :status
        delete :remove_slot
      end
    end
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < TranscoderManagerController

  def index
    tm_get('events') do |resp|
      @events = resp.map { |atts| TMEvent.new(atts) }.sort_by! { |x| x.name }
    end
  end

  def show
    tm_get("events/#{params[:id]}") do |resp|
      @event = TMEvent.new(resp)
    end
    tm_get("events/#{params[:id]}/slots") do |resp|
      @slots = resp.map { |atts| TMSlot.new(atts) }.sort
    end
    tm_get('transcoders') do |resp|
      @transcoders = resp.map { |atts| TMTranscoder.new(atts) }.sort_by! { |x| x.name }
    end
  end

  def new
    if params[:id]
      tm_get("events/#{params[:id]}") do |resp|
        @event = TMEvent.new(resp)
      end
    else
      @event = TMEvent.new
    end
  end

  def create
    tm_post('events', {params: params[:tm_event].to_hash}) do
      redirect_to admin_events_url, notice: 'Event created successfully'
    end
  end

  def edit
    tm_get("events/#{params[:id]}") do |resp|
      @event = TMEvent.new(resp)
    end
  end

  def update
    tm_put("events/#{params[:id]}", {params: params[:tm_event].to_hash}) do
      redirect_to admin_event_path(id: params[:id]), notice: 'Event updated successfully'
    end
  end

  def destroy
    tm_delete("events/#{ params[:id] }") do
      redirect_to admin_events_url, notice: 'Event deleted successfully'
    end
  end

  def action
    redirect_options = {action: :show, id: params[:id]}
    tm_get("events/#{params[:id]}/#{params[:command]}",
           {fail_redirect: redirect_options}) do
      redirect_to(redirect_options)
    end
  end

  def add_slot
    redirect_options = {action: :show, id: params[:id]}
    tm_post("events/#{params[:id]}/slots",
            {params: {slot_id: params[:slot_id]}, fail_redirect: redirect_options}) do
      redirect_to(redirect_options, notice: 'Slot added successfully')
    end
  end

  def remove_slot
    redirect_options = {action: :show, id: params[:id]}
    tm_delete("events/#{params[:id]}/slots/#{params[:slot_id]}",
              {fail_redirect: redirect_options}) do
      redirect_to(redirect_options, notice: 'Slot removed successfully')
    end
  end

  def status
    url = "events/#{params[:id]}/status"
    url += "?with_slots=#{params[:with_slots]}" if params[:with_slots]
    tm_get(url, {parse_body: false}) do |resp|
      @json = resp.body
      @statuses = JSON.parse resp.body
    end

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @json }
    end
  end
end

app/views/admin/events/edit.html.haml
= content_for :breadcrumb do
  %li
    = link_to 'Home' , '/'
    %span.divider /
  %li
    = link_to 'Events' , admin_events_path
    %span.divider /
  %li
    = link_to @event.name , admin_event_path(id: @event.id)
    %span.divider /
  %li.active Edit

.row-fluid
  = simple_form_for [:admin, @event], url: admin_event_path(id: @event.id), method: :put do |f|
    = display_errors f
    = f.input :name, label: 'Display name'
    = f.input :csid, label: 'Cross System ID'
    = display_actions f, admin_event_path(id: @event.id)

app/views/admin/events/index.html.haml
= content_for :breadcrumb do
  %li
    = link_to 'Home' , '/'
    %span.divider /
  %li.active Events

%p
  = link_to 'New Event', new_admin_event_path, :class => 'btn btn-success btn-large pull-right'
.row-fluid
  %table.table
    %thead
      %tr
        %th Name
        %th CSID
        %th Actions
    %tbody
      - @events.each do |event|
        %tr
          %td= event.name
          %td= event.csid
          %td
            = link_to 'Show', admin_event_path(id: event.id)
            \|
            = link_to 'Edit', edit_admin_event_path(id: event.id)
            \|
            = link_to 'Copy', new_admin_event_path(id: event.id)
            \|
            = link_to 'Destroy', admin_event_path(id: event.id), :class => 'label label-important', :confirm => 'Are you sure?', :method => :delete

app/views/admin/events/new.html.haml
= content_for :breadcrumb do
  %li
    = link_to 'Home' , '/'
    %span.divider /
  %li
    = link_to 'Events' , admin_events_path
    %span.divider /
  %li.active New Event

= simple_form_for [:admin, @event], url: admin_events_path, method: :post do |f|
  = display_errors f
  = f.input :name, label: 'Display name'
  = f.input :csid, label: 'Cross System ID'
  = display_actions f, admin_events_url

app/views/admin/events/show.html.haml
= content_for :breadcrumb do
  %li
    = link_to 'Home' , '/'
    %span.divider /
  %li
    = link_to 'Events' , admin_events_path
    %span.divider /
  %li.active= @event.name

.subnav
  %ul.nav.nav-pills
    %li
      = link_to 'Edit', edit_admin_event_path(id: @event.id)
    %li
      = link_to 'Copy', new_admin_event_path(id: @event.id)
    %li
      = link_to 'Destroy', admin_event_path(id: @event.id), :class => 'label label-important', :confirm => 'Are you sure?', :method => :delete

.row-fluid
  .span4.well
    = display_show_item('ID', @event.id)
    = display_show_item('Name', @event.name)
    = display_show_item('CSID', @event.csid)
    = display_show_item('Number of Slots', @slots.length)
  .span8
    .row-fluid#event_status
    .row-fluid
      %button#event_off.btn.btn-danger
        %i.icon-align-left.icon-stop
        Off
      %button#event_ready.btn.btn-info
        %i.icon-align-left.icon-check
        Ready
      %button#event_on.btn.btn-success
        %i.icon-align-left.icon-play
        On

.row-fluid
  .span2
    %h3 Slots:
  %span.pull-right
    = link_to 'Add Slot', '#slotModal', class: 'btn btn-success btn-large', :'data-toggle' => 'modal'

.row-fluid
  %table.table.table-bordered.table-condensed
    %thead
      %tr
        %th Transcoder
        %th Slot id
        %th Scheme
        %th Actions
    %tbody
      - @slots.each do |s|
        %tr
          %td{width: '100px'}= link_to s.transcoder_name, admin_transcoder_path(id: s.transcoder_id)
          %td{width: '25px'}= s.slot_id
          %td{width: '100px'}= link_to s.scheme_name, admin_scheme_path(id: s.scheme_id)
          %td{width: '60px'}= link_to 'remove', remove_slot_admin_event_path(slot_id: s.id),
          :class => 'label label-important',:method => :delete

%div#slotModal.modal.hide.fade{tabindex: -1, role: 'dialog', :'aria-labelledby' => 'slot label', :'aria-hidden' => 'true'}
  %form#slotForm.form-horizontal{action: add_slot_admin_event_path}
    %div.modal-header
      %button.close{type: 'button', :'data-dismiss' => 'modal', :'aria-hidden' => 'true'}
        x
      %h3 Add Slot
    %div.modal-body
      %p.text-error{id:'slots_message', style: 'display:none;'}
      %fieldset
        %div.control-group
          %label.control-label{for: 'slotModalTranscoder'}  Transcoder
          %div.controls
            %select#slotModalTranscoder{name: 'tx_id'}
              - @transcoders.each do |txcoder|
                %option{value: txcoder.id}
                  = txcoder.name
        %div.control-group
          %label.control-label{for: 'slotModalSlot'}  Slot
          %div.controls
            %select#slotModalSlot{name: 'slot_id'}
    %div.modal-footer
      %button.btn{:'data-dismiss' => 'modal', :'aria-hidden' => 'true'} cancel
      %button#slotModalSave.btn.btn-primary Save

:javascript
  bb.show_event(#{ @event.id });