config/routes.rb
BroadcastWeb::Application.routes.draw do

  root to: 'pages#home'

  get 'transcoder_console', controller: :TranscoderConsole, action: :index
  post 'transcoder_console/perform'

  get 'transcoder_test', controller: :TranscoderTest, action: :index
  post 'transcoder_test/perform'
  get 'transcoder_test/status'
  get 'transcoder_test/host',controller: :TranscoderTest, action: :change_transcoder

  get 'advanced', controller: :Pages, action: :advanced
  get 'monitoring', controller: :Pages, action: :monitoring

  get '/admin/', controller: :Pages, action: :admin

  namespace :admin do
    resources :captures
    resources :sources
    resources :presets
    resources :schemes

    resources :transcoders do
      member do
        get :action
        get :create_slot
        get :start_slot
        get :stop_slot
        get :slots_status
        get :get_slots
        delete :delete_slot
      end
    end

    resources :events do
      member do
        get :action
        get :add_slot
        get :status
        delete :remove_slot
      end
    end
  end

end

app/models/transcoder.rb
class Transcoder < ActiveRecord::Base
  after_find :init_transcoder

  # attributes

  has_many :slot_presets, dependent: :destroy

  attr_accessible :host, :port

  attr_accessor :api

  # callbacks

  def init_transcoder
    @api = TranscoderApi.new(host: host, port: port)
  end

  # public methods

  def current_slot_ids
    result = TranscoderApiCommand.new(TranscoderApi::MOD_GET_SLOTS, {}).execute self
    ids = result[:error] == TranscoderApi::RET_OK ? result[:result][:slots_ids] : nil
    ids.nil? ? [] : ids
  end

  def get_status
    current_slot_ids.map { |id|
      TranscoderApiCommand.new(TranscoderApi::MOD_SLOT_CMD,
                               {slot_cmd: TranscoderApi::CMD_SLOT_GET_STATUS, slot_id: id}) }
    .map {|api_cmd| [api_cmd, api_cmd.execute(self)]}
    .each do |cmd, result|
      slot_id = cmd.args[:slot_id]
      result[:slot_id] = slot_id
      result[:preset] = slot_preset(slot_id).name
      result[:link] = slot_link slot_id
    end
  end

  def create_slot(slot_id, preset)
    slot_preset = slot_presets.where(slot_id: slot_id).first_or_create!
    slot_preset.preset_id = preset.id
    slot_preset.save!
  end

  def remove_slot(slot_id)
    slot_presets.where(slot_id: slot_id).destroy_all
  end

  def slot_preset(slot_id)
    preset_id = slot_presets.where(slot_id: slot_id).first!.preset_id
    preset = TranscoderManager.instance.get_preset_by_id(preset_id)
    preset.nil? ? Preset.find(preset_id) : preset
  end

  def slot_link(slot_id)
    "http://#{host}:#{8000 + slot_id}"
  end

end

app/controllers/admin/transcoders_controller.rb
class Admin::TranscodersController < TranscoderManagerController

  def index
    tm_get('transcoders') do |resp|
      @transcoders = resp.map { |atts| TMTranscoder.new(atts) }.sort_by! { |x| x.name }
    end
  end

  def show
    tm_get("transcoders/#{params[:id]}") do |resp|
      @transcoder = TMTranscoder.new(resp)
    end
    tm_get("transcoders/#{params[:id]}/slots") do |resp|
      @slots = resp.map { |atts| TMSlot.new(atts) }.sort
    end
    tm_get('schemes') do |resp|
      @schemes = resp.map { |atts| TMScheme.new(atts) }.sort_by! { |x| x.name }
    end
  end

  def new
    if params[:id]
      tm_get("transcoders/#{params[:id]}") do |resp|
        @transcoder = TMTranscoder.new(resp)
      end
    else
      @transcoder = TMTranscoder.new
    end
  end

  def create
    tm_post('transcoders', {params: params[:tm_transcoder].to_hash}) do
      redirect_to admin_transcoders_url, notice: 'Transcoder created successfully'
    end
  end

  def edit
    tm_get("transcoders/#{params[:id]}") do |resp|
      @transcoder = TMTranscoder.new(resp)
    end
  end

  def update
    tm_put("transcoders/#{params[:id]}", {params: params[:tm_transcoder].to_hash}) do
      redirect_to admin_transcoder_path(id: params[:id]), notice: 'Transcoder updated successfully'
    end
  end

  def destroy
    tm_delete("transcoders/#{ params[:id] }") do
      redirect_to admin_transcoders_url, notice: 'Transcoder deleted successfully'
    end
  end

  def action
    redirect_options = {action: :show, id: params[:id]}
    tm_get("transcoders/#{params[:id]}/#{params[:command]}",
           {fail_redirect: redirect_options}) do |resp|
      redirect_to(redirect_options, notice: resp)
    end
  end

  def create_slot
    atts = {
        slot_id: params[:slot_id],
        scheme_id: params[:scheme_id]
    }
    redirect_options = {action: :show, id: params[:id]}
    tm_post("transcoders/#{params[:id]}/slots",
            {params: atts, fail_redirect: redirect_options}) do
      redirect_to(redirect_options, notice: 'Slot created successfully')
    end
  end

  def delete_slot
    redirect_options = {action: :show, id: params[:id]}
    tm_delete("transcoders/#{params[:id]}/slots/#{params[:slot_id]}",
              {fail_redirect: redirect_options}) do
      redirect_to(redirect_options, notice: 'Slot deleted successfully')
    end
  end

  def start_slot
    redirect_options = {action: :show, id: params[:id]}
    tm_get("transcoders/#{params[:id]}/slots/#{params[:slot_id]}/start",
           {fail_redirect: redirect_options}) do
      redirect_to redirect_options
    end
  end

  def stop_slot
    redirect_options = {action: :show, id: params[:id]}
    tm_get("transcoders/#{params[:id]}/slots/#{params[:slot_id]}/stop",
           {fail_redirect: redirect_options}) do
      redirect_to redirect_options
    end
  end

  def get_slots
    tm_get("transcoders/#{params[:id]}/slots",
           {fail_redirect: false, parse_body: false}) do |resp, alert|
      render_json_api_response resp, alert
    end
  end

  def slots_status
    tm_get("transcoders/#{params[:id]}/slots/status",
           {fail_redirect: false, parse_body: false}) do |resp, alert|
      render_json_api_response resp, alert
    end
  end

end

app/views/admin/transcoders/edit.html.haml
= content_for :breadcrumb do
  %li
    = link_to 'Home' , '/'
    %span.divider /
  %li
    = link_to 'Transcoders' , admin_transcoders_path
    %span.divider /
  %li
    = link_to @transcoder.name , admin_transcoder_path(id: @transcoder.id)
    %span.divider /
  %li.active Edit

.row-fluid
  = simple_form_for [:admin, @transcoder], url: admin_transcoder_path(id: @transcoder.id), method: :put do |f|
    = display_errors f

    = f.input :name, label: 'Display name'
    = f.input :host, label: 'Host ip address'
    = f.input :port, label: 'Binary api port'
    = f.input :status_port, label: 'Load status port'

    = display_actions f, admin_transcoder_path(id: @transcoder.id)

app/views/admin/transcoders/index.html.haml
= content_for :breadcrumb do
  %li
    = link_to 'Home' , '/'
    %span.divider /
  %li.active Transcoders

%p
  = link_to 'New Transcoder', new_admin_transcoder_path, :class => 'btn btn-success btn-large pull-right'
.row-fluid
  %table.table
    %thead
      %tr
        %th Name
        %th Host
        %th Port
        %th Status Port
        %th Actions
    %tbody
      - @transcoders.each do |txcoder|
        %tr
          %td= txcoder.name
          %td= txcoder.host
          %td= txcoder.port
          %td= txcoder.status_port
          %td
            = link_to 'Show', admin_transcoder_path(id: txcoder.id)
            \|
            = link_to 'Edit', edit_admin_transcoder_path(id: txcoder.id)
            \|
            = link_to 'Copy', new_admin_transcoder_path(id: txcoder.id)
            \|
            = link_to 'Destroy', admin_transcoder_path(id: txcoder.id), :class => 'label label-important',
              :confirm => 'This will remove statistics as well. Are you sure?', :method => :delete

app/views/admin/transcoders/new.html.haml
= content_for :breadcrumb do
  %li
    = link_to 'Home' , '/'
    %span.divider /
  %li
    = link_to 'Transcoders' , admin_transcoders_path
    %span.divider /
  %li.active New Transcoder

= simple_form_for [:admin, @transcoder], url: admin_transcoders_path, method: :post do |f|
  = display_errors f

  = f.input :name, label: 'Display name'
  = f.input :host, label: 'Host ip address'
  = f.input :port, label: 'Binary api port'
  = f.input :status_port, label: 'Load status port'

  = display_actions f, admin_transcoders_url

app/views/admin/transcoders/show.html.haml
= content_for :breadcrumb do
  %li
    = link_to 'Home' , '/'
    %span.divider /
  %li
    = link_to 'Transcoders' , admin_transcoders_path
    %span.divider /
  %li.active= @transcoder.name

.subnav
  %ul.nav.nav-pills
    %li
      = link_to 'Edit', edit_admin_transcoder_path(id: @transcoder.id)
    %li
      = link_to 'Copy', new_admin_transcoder_path(id: @transcoder.id)
    %li
      = link_to 'Destroy', admin_transcoder_path(id: @transcoder.id), :class => 'label label-important',
      :confirm => 'This will remove statistics as well. Are you sure?', :method => :delete

.row-fluid
  .span4.well
    = display_show_item('ID', @transcoder.id)
    = display_show_item('Name', @transcoder.name)
    = display_show_item('Host', @transcoder.host)
    = display_show_item('Port', @transcoder.port)
    = display_show_item('Status Port', @transcoder.status_port)
    = display_show_item('Number of Slots', @slots.length)
  .span8
    = link_to 'Save Config', action_admin_transcoder_path(command: :save) ,class: 'btn'
    %p Saves the current configuration state on the transcoder.
    = link_to 'Restart', action_admin_transcoder_path(command: :restart) ,class: 'btn'
    %p Restarts the transcoder. Returns to the saved configuration, not current.
    = link_to 'Sync Config', action_admin_transcoder_path(command: :sync) ,class: 'btn'
    %p
      Synchronize the actual, current, configuration on the transcoder
      with the saved configuration in the Transcoder Manager.

.row-fluid
  .span2
    %h3 Slots:
  %span.pull-right
    = link_to 'New Slot', '#slotModal', class: 'btn btn-success btn-large', :'data-toggle' => 'modal'
  %span.text-error{id:'slots_message', style: 'display:none;'}

.row-fluid
  %table.table.table-bordered.table-condensed
    %thead
      %tr
        %th Slot_id
        %th Scheme
        %th Link
        %th State
        %th{colspan: 2, width: '120px'} Actions
    %tbody
      - @slots.each do |s|
        %tr
          %td{width: '25px'}= s.slot_id
          %td{width: '100px'}= link_to s.scheme_name, admin_scheme_path(id: s.scheme_id)
          %td{width: '70px'}= "http://#{@transcoder.host}:#{8000 + s.slot_id}"
          %td{id: "slot_state_#{s.slot_id}", width: '250px'}
          %td{id: "slot_action_#{s.slot_id}", width: '60px'}
          %td{width: '60px'}= link_to 'delete', delete_slot_admin_transcoder_path(slot_id: s.id), :class => 'label label-important',:method => :delete

%div#slotModal.modal.hide.fade{tabindex: -1, role: 'dialog', :'aria-labelledby' => 'slot label', :'aria-hidden' => 'true'}
  %form#slotForm.form-horizontal{action: create_slot_admin_transcoder_path}
    %div.modal-header
      %button.close{type: 'button', :'data-dismiss' => 'modal', :'aria-hidden' => 'true'}
        x
      %h3 New Slot
    %div.modal-body
      %fieldset
        %div.control-group
          %label.control-label{for: 'slotModalSlotId'}  Slot Id
          %div.controls
            %input#slotModalSlotId{type: 'text', name: 'slot_id',value: ''}
            %span.help-block range: 0-255, make sure id is not taken.
        %div.control-group
          %label.control-label{for: 'slotModalScheme'}  Scheme
          %div.controls
            %select#slotModalScheme{name: 'scheme_id'}
              - @schemes.each do |scheme|
                %option{value: scheme.id}
                  = scheme.name
    %div.modal-footer
      %button.btn{:'data-dismiss' => 'modal', :'aria-hidden' => 'true'}
        cancel
      %button#slotModalSave.btn.btn-primary
        Save

:javascript
  bb.show_transcoder(#{ @transcoder.id });