config/routes.rb
BroadcastWeb::Application.routes.draw do

  root to: 'pages#home'

  get 'transcoder_console', controller: :TranscoderConsole, action: :index
  post 'transcoder_console/perform'

  get 'transcoder_test', controller: :TranscoderTest, action: :index
  post 'transcoder_test/perform'
  get 'transcoder_test/status'
  get 'transcoder_test/host',controller: :TranscoderTest, action: :change_transcoder

  get 'advanced', controller: :Pages, action: :advanced
  get 'monitoring', controller: :Pages, action: :monitoring

  get '/admin/', controller: :Pages, action: :admin

  namespace :admin do
    resources :captures
    resources :sources
    resources :presets
    resources :schemes

    resources :transcoders do
      member do
        get :action
        get :create_slot
        get :start_slot
        get :stop_slot
        get :slots_status
        get :get_slots
        delete :delete_slot
      end
    end

    resources :events do
      member do
        get :action
        get :add_slot
        get :status
        delete :remove_slot
      end
    end
  end

end

app/controllers/admin/sources_controller.rb
class Admin::SourcesController < TranscoderManagerController

  def index
    tm_get('sources') do |resp|
      @sources = resp.map { |atts| TMSource.new(atts) }.sort_by! { |x| x.name }
    end
  end

  def show
    tm_get("sources/#{params[:id]}") do |resp|
      @source = TMSource.new(resp)
    end
  end

  def new
    if params[:id]
      show
    else
      @source = TMSource.new
    end
    tm_get('captures') do |resp|
      @captures = resp.map { |atts| TMCapture.new(atts) }.sort_by! { |x| x.name }
    end
  end

  def create
    tm_post('sources', {params: params[:tm_source].to_hash}) do
      redirect_to admin_sources_url, notice: 'Source created successfully'
    end
  end

  def edit
    tm_get("sources/#{params[:id]}") do |resp|
      @source = TMSource.new(resp)
    end
    tm_get('captures') do |resp|
      @captures = resp.map { |atts| TMCapture.new(atts) }.sort_by! { |x| x.name }
    end
  end

  def update
    tm_put("sources/#{params[:id]}", {params: params[:tm_source].to_hash}) do
      redirect_to admin_source_path(id: params[:id]), notice: 'Source updated successfully'
    end
  end

  def destroy
    tm_delete("sources/#{ params[:id] }") do
      redirect_to admin_sources_url, notice: 'Source deleted successfully'
    end
  end

end

app/views/admin/sources/edit.html.haml
= content_for :breadcrumb do
  %li
    = link_to 'Home' , '/'
    %span.divider /
  %li
    = link_to 'Sources' , admin_sources_path
    %span.divider /
  %li
    = link_to @source.name , admin_source_path(id: @source.id)
    %span.divider /
  %li.active Edit

= simple_form_for [:admin, @source], url: admin_source_path(id: @source.id), method: :put do |f|
  = display_errors f

  = f.input :name, label: 'Display name'

  = f.input :capture_id,
    as: :select,
    label: 'Capture',
    collection: @captures,
    label_method: lambda {|c| c.name},
    value_method: lambda {|c| c.id},
    include_blank: false

  = f.input :input,
    as: :select,
    label: 'Input',
    collection: (1..4),
    include_blank: false

  = display_actions f, admin_source_path(id: @source.id)

app/views/admin/sources/index.html.haml
= content_for :breadcrumb do
  %li
    = link_to 'Home' , '/'
    %span.divider /
  %li.active Sources

%p
  = link_to 'New Source', new_admin_source_path, :class => 'btn btn-success btn-large pull-right'
.row-fluid
  %table.table
    %thead
      %tr
        %th Name
        %th Capture
        %th Input
        %th Actions
    %tbody
      - @sources.each do |source|
        %tr
          %td= source.name
          %td= link_to source.capture_name, admin_capture_path(id: source.capture_id)
          %td= source.input
          %td
            = link_to 'Show', admin_source_path(id: source.id)
            \|
            = link_to 'Edit', edit_admin_source_path(id: source.id)
            \|
            = link_to 'Copy', new_admin_source_path(id: source.id)
            \|
            = link_to 'Destroy', admin_source_path(id: source.id), :class => 'label label-important', :confirm => 'Are you sure?', :method => :delete

app/views/admin/sources/new.html.haml
= content_for :breadcrumb do
  %li
    = link_to 'Home' , '/'
    %span.divider /
  %li
    = link_to 'Sources' , admin_sources_path
    %span.divider /
  %li.active New Source

= simple_form_for [:admin, @source], url: admin_sources_path, method: :post do |f|
  = display_errors f

  = f.input :name, label: 'Display name'

  = f.input :capture_id,
      as: :select,
      label: 'Capture',
      collection: @captures,
      label_method: lambda {|c| c.name},
      value_method: lambda {|c| c.id},
      include_blank: false

  = f.input :input, label: 'Input', collection: (1..4)

  = display_actions f, admin_sources_url

app/views/admin/sources/show.html.haml
= content_for :breadcrumb do
  %li
    = link_to 'Home' , '/'
    %span.divider /
  %li
    = link_to 'Sources' , admin_sources_path
    %span.divider /
  %li.active= @source.name

.subnav
  %ul.nav.nav-pills
    %li
      = link_to 'Edit', edit_admin_source_path(id: @source.id)
    %li
      = link_to 'Copy', new_admin_source_path(id: @source.id)
    %li
      = link_to 'Destroy', admin_source_path(id: @source.id), :class => 'label label-important', :confirm => 'Are you sure?', :method => :delete

.row-fluid
  .span6.well
    = display_show_item('ID', @source.id)
    = display_show_item('Name', @source.name)
    = display_show_item('Capture', link_to(@source.capture_name, admin_capture_path(@source.capture_id)), true)
    = display_show_item('Input', @source.input)