config/routes.rb
BroadcastWeb::Application.routes.draw do

  root to: 'pages#home'

  get 'transcoder_console', controller: :TranscoderConsole, action: :index
  post 'transcoder_console/perform'

  get 'transcoder_test', controller: :TranscoderTest, action: :index
  post 'transcoder_test/perform'
  get 'transcoder_test/status'
  get 'transcoder_test/host',controller: :TranscoderTest, action: :change_transcoder

  get 'advanced', controller: :Pages, action: :advanced
  get 'monitoring', controller: :Pages, action: :monitoring

  get '/admin/', controller: :Pages, action: :admin

  namespace :admin do
    resources :captures
    resources :sources
    resources :presets
    resources :schemes

    resources :transcoders do
      member do
        get :action
        get :create_slot
        get :start_slot
        get :stop_slot
        get :slots_status
        get :get_slots
        delete :delete_slot
      end
    end

    resources :events do
      member do
        get :action
        get :add_slot
        get :status
        delete :remove_slot
      end
    end
  end

end

app/helpers/layout_helper.rb
module LayoutHelper

  def display_show_item(name, value, as_is = false)
    engine = Haml::Engine.new <<-HAML
%p
  %strong #{name.humanize}:
  #{as_is ? value : value.to_s.gsub(/\s/, '&nbsp;')}
    HAML
    engine.render
  end

  def display_actions(f, location)
    engine = Haml::Engine.new <<-HAML
.actions
  %button.btn.btn-primary{:type => 'submit', :'data-disable-with' => 'Please wait...'} Save
  %button.btn.btn-link{:onclick => "location.href='#{location}'; return false;", :type => 'button'} Cancel
    HAML
    engine.render self, :form => f
  end

  def display_errors(f)
    engine = Haml::Engine.new <<-HAML
- if form.error_notification
  .alert.alert-error.fade.in
    %a.close(data-dismiss="alert" href="#") &times;
    = form.error_notification :class => 'no-margin'
  %hr.soften
    HAML
    engine.render self, :form => f
  end
end

app/views/layouts/_navigation.html.haml
.navbar
  .navbar-inner
    .container
      = link_to  '/', :class => 'brand' do
        = image_tag 'bb.png', size: '32x32'
        &nbsp;&nbsp;&nbsp;
        BB Web Broadcast

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:charset=>'utf-8'}
    %title
      = content_for?(:title) ? yield(:title) : 'BB Web Broadcast'
    %meta{:content=>'width=device-width, initial-scale=1.0', :name=>'viewport'}/
    %meta{'http-equiv'=>'Content-Type', :content=>'text/html; charset=utf-8'}/
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tag
    = yield(:head)
  %body
    = render 'layouts/navigation'
    .container-fluid
      .row-fluid
        .span2
          %ul.nav.nav-list
            %li.nav-header Configuration
            %li= link_to 'Events', admin_events_path
            %li= link_to 'Transcoders', admin_transcoders_path
            %li= link_to 'Schemes', admin_schemes_path
            %li= link_to 'Presets', admin_presets_path
            %li= link_to 'Sources', admin_sources_path
            %li= link_to 'Captures', admin_captures_path

            %li.nav-header Advanced
            %li= link_to 'Maintenance', advanced_path
            %li= link_to 'Monitoring', monitoring_path

            -#%li.nav-header Old stuff
            -#%li= link_to 'Transcoder test', transcoder_test_path
            -#%li= link_to 'Transcoder console', transcoder_console_path

        .span10
          %ul.breadcrumb
            =yield(:breadcrumb)
          - flash.each do |name, msg|
            - klass = (name.to_s == 'error' || name.to_s == 'alert') ? 'alert fade in alert-error' : 'alert fade in alert-info'
            = content_tag :div, "<a class='close' data-dismiss='alert' href='#'>&times;</a>#{msg}".html_safe, :class => klass
          = yield

app/views/layouts/nomenu_layout.html.haml
!!! 5
%html
  %head
    %meta{:charset=>'utf-8'}
    %title
      = content_for?(:title) ? yield(:title) : 'BB Web Broadcast'
    %meta{:content=>'width=device-width, initial-scale=1.0', :name=>'viewport'}/
    %meta{'http-equiv'=>'Content-Type', :content=>'text/html; charset=utf-8'}/
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tag
    = yield(:head)
  %body
    = render 'layouts/navigation'
    - flash.each do |name, msg|
      - klass = (name.to_s == 'error' || name.to_s == 'alert') ? 'alert fade in alert-error' : 'alert fade in alert-info'
      = content_tag :div, "<a class='close' data-dismiss='alert' href='#'>&times;</a>#{msg}".html_safe, :class => klass
    = yield